### ISSUE TITLE
HvLightPipe.c errors

### ISSUE THREAD

**Issue by heni40** [enzienaudio/heavy#97]
Hi,
there popped up a new error I haven´t seen, yet. After compiling the same patch as a C Source, there is a new hvlightpipe class which is not compiling in VS2015. 
The error is: 
'**asm**': undeclared identifier
syntax error: missing ';' before 'volatile'
both in Line 87 and again in 105 in the HvLightPipe.c File.

this is frustrating, because I had everything up and running and now the new class breaks it.
hv_sfence() is defined as follows:
# define hv_sfence() **asm** volatile("" : : : "memory")

that must be the problem... But as I am kind of a C beginner, I can´t figure it out myself.

Any help would be appreciated.
Thanks,
Hendrik

**Comment by mhroth** [comment]
Hi @heni40. If you're trying to compile from scratch in VS2015, be sure to add the `HV_SIMD_SSE` flag to the C preprocessor. You can also look at any of the VS2015 projects that we generate as a template.

**Comment by heni40** [comment]
Hi mhroth, 
thank you for the reply. Did that, now I got problems with my biquads and cpole filters.
The error is something like this:
Severity    Code    Description Project File    Line    Suppression State
Error   C2719   'bX2': formal parameter with requested alignment of 16 won't be aligned

Any suggestions?
Thx

**Comment by mhroth** [comment]
You can solve this problem by compiling in 64-bit mode i.e. `x64`. If you absolutely have to compile for 32-bit mode i.e. `x86` then unfortunately I don't yet know how to solve this problem.

**Comment by heni40** [comment]
ok, got it running in x64 mode. It now crashes every time I use hv_vscheduleMessageForReceiver.
I´m using it to compile a JUCE Plugin and test it with the JUCE Plugin Host (also now compiled for x64). Maybe this helps sorting this out.

**Comment by heni40** [comment]
Just tried it in Reaper x64. That works. So must be something with the JUCE Plugin Host. gonna have to figure that problem out. But thanks so far!!

**Comment by mhroth** [comment]
You are trying to make an audio plugin e.g. a VST2? Try downloading our VST2 source for your patch and see how we structured the project. You can also try the VST2 (e.g. with Reaper64) to it working live.

If you're only trying to send a single float value into the context, try using the convenience function `hv_sendFloatToReceiver()`.

**Comment by mhroth** [comment]
BTW I've also added a change so that you can compile in 32-bit mode, in case you need to. You'll have to recompile to get the new code. Let me know if you have any questions!

**Comment by heni40** [comment]
I am combining different patches in a JUCE Plugin Project to be able to build VST, VST3 and AU Plugins for OSX and Windows. 
So the build that ran on reaper yesterday actually didn´t run. I loaded the 32-bit VST version from before. My mistake. I can now compile a 64 bit Version and also got it running.
2 problems still occur and I have no clue how to solve them right now.

1: it still crashes everytime I send some kind of message (hv_sendFloatToReceiver()) (just holds with no debug message and I have to kill the JUCE host I have running also in debug mode)

2: it crashes as soon as I use the process function. There the problem lies in the "static inline void __hv_store_f(float *bOut, hv_bInf_t bIn)" function with the HV_SIMD_SSE flag.

I am new to the whole SSE / 64bit stuff. First time I am confronted with this. It is just a little frustrating because I got it all running but now after recompiling some patches it does not work anymore. 

I tried recompiling and doing it as I did 2 days ago with 32 bit and no HV_SIMD_SSE flag as it worked there. But same problems with the LightPipe. How can I explicitly compile the Patches in 32bit mode, what you mentioned in your last post?
Thanks!!

**Comment by mhroth** [comment]
I'll get back to you when I have more information, but in the meantime your second issue with `__hv_store_f` is very atypical. Are you sure that you're using the correct version of `process()` in JUCE? I.e. `process()`, `process_inline()` or `process_inline_interleaved()`

**Comment by heni40** [comment]
yes, I´m pretty sure I do that right. It worked before, so I´m quite confident.

I got a step further. I got two patches in there.
1st patch: 0 Inputs, 3 Outputs.
2nd patch: 3 inputs, 3 outputs.

It works when I deactivate patch 2. I have `nullptr` as inputBuffer and a 3 channel `JUCE::AudioBuffer<float>` (which is basicly an Array of float Sample Arrays) as Output Buffer. When I load the VST the process function works.

the 2nd Patch is where it gets ugly and I can´t spot any errors. I preallocated two seperate buffers with 3 channels each. Even when I run the second patch by its own it crashes during process during the `int hTable_resize(HvTable *o, hv_uint32_t newLength)` function in the line `float *b = (float *) hv_realloc(o->buffer, newBytes);`

the message error is something complete different I suppose.

would it help to see the patches or the whole code?

**Comment by heni40** [comment]
The problem is indeed the `JUCE::AudioBuffer<float>`. I tried it the way it is written in the C API example and created a `float **inBuffer`. That actually does work. It actually did work before the switch to 64-bit. It sadly is much more work to allocate and deallocate the buffers all by hand and not being able to use the JUCE class.

**edit:**
only worked with small test patch... the actual thing still won´t work...

**Comment by mhroth** [comment]
@heni40 I pushed a small change which will allow you to compile Heavy in Win32 (x86) mode with `HV_SIMD_SSE` enabled. You can now avoid the `formal parameter with requested alignment of 16 won't be aligned` error. You'll need to recompile your patch to get the changes. Maybe this will help you?

Unfortunately your other errors don't necessarily suggest any error within heavy itself (though the errors are happening within heavy), rather potentially an error in gluing together JUCE and heavy. The only thing that I can think of is that if you don't `process` heavy, then messages will also not be processed and if you keep sending it messages, they will eventually overflow the message queue and/or pool.

If you want, send me a _self contained_ project (perhaps via Dropbox) at `info@enzienaudio.com`.

**Comment by heni40** [comment]
@mhroth makes sense with the messages. 
the `formal parameter with requested alignment of 16 won't be aligned` error is still there, but not so many. Before it was in the signalbiquad.h and signalcpole.h files. Now only in the signalcpole.h files.

**Comment by mhroth** [comment]
Would you please send me the enzien link to your patch?

**Comment by heni40** [comment]
sent it via email

**Comment by heni40** [comment]
it runs under xcode, but only without the `HV_SIMD_SSE` flag. Is this flag VS specific?

**Comment by mhroth** [comment]
I feel like you have a lot of different things all going wrong at once. Forget about `HV_SIMD_SSE` for now, as you said that you weren't that comfortable with SSE. Pass the `HV_SIMD_NONE` flag to both Xcode and VS. It will maximise the chances of making it work.

**Comment by mhroth** [comment]
@heni40 I've had another chance to look at your plugin. I tried compiling the patch that you sent me as a 32-bit Windows VST, and it seems to work fine. Have you seen our [JUCE examples](https://github.com/enzienaudio/examples/tree/master/juce/audio_plugin)? The Heavy `process` function is called [here](https://github.com/enzienaudio/examples/blob/master/juce/audio_plugin/Source/PluginProcessor.cpp#L161) using [AudioBuffer::getArrayOfWritePointers](https://www.juce.com/doc/classAudioBuffer#a6f52c02a21eb14d53e2a6fa46a825f4f).

**Comment by heni40** [comment]
Hi mhroth, thanks I saw that example. And thats exactly how I implemented it. It currently works fine in 64-bit with the `HV_SIMD_NONE` flag. So right now I am gonna stick with that. 
Thank you for all the help. And thank you for the nice heavy compiler!!

**Comment by mhroth** [comment]
Great! I'm glad that it worked out.
